version: "3.8"
services:
  satisfactory:
    image: paultrampert/satisfactory:experimental
    ports:
      - "15777:15777/udp"
      - "15000:15000/udp"
      - "7777:7777/udp"
    volumes:
      - "satisfactory_data:/home/steam/.config/Epic/FactoryGame/Saved/"
volumes:
  satisfactory_data: